services:
  jaeger:
    image: jaegertracing/all-in-one:1.49
    environment:
      COLLECTOR_ZIPKIN_HOST_PORT: "9411"
      COLLECTOR_OTLP_ENABLED: "true"
    ports:
      - 6831:6831/udp
      - 6832:6832/udp
      - 5778:5778
      - 16686:16686 # UI
      - 4317:4317
      - 4318:4318
      - 14250:14250
      - 14268:14268
      - 14269:14269
      - 9411:9411

  db:
    image: postgres
    volumes:
      - db-data:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    environment:
      POSTGRES_PASSWORD: password

  api:
    build: api
    ports:
      - "3000:3000"
    depends_on:
      - jaeger
      - db
    environment:
      OTEL_SERVICE_NAME: api-service
      OTEL_EXPORTER_OTLP_TRACES_ENDPOINT: http://jaeger:4317
      RUST_LOG: info,axum_tracing_opentelemetry=info,otel=debug

  website:
    build: website
    ports:
      - "8000:8000"
    depends_on:
      - api
    environment:
      OTEL_SERVICE_NAME: api-service
      OTEL_EXPORTER_OTLP_TRACES_ENDPOINT: http://jaeger:4317
      RUST_LOG=info,axum_tracing_opentelemetry: info,otel=debug

volumes:
  db-data:
