/*
 * 
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.0.1
 * 
 * Generated by: https://openapi-generator.tech
 */




#[derive(Clone, Debug, PartialEq, Serialize, Deserialize)]
pub struct SendCode {
    #[serde(rename = "mobile")]
    pub mobile: String,
}

impl SendCode {
    pub fn new(mobile: String) -> SendCode {
        SendCode {
            mobile,
        }
    }
}


