[package]
name = "website"
version = "0.1.0"
edition = "2021"
publish = false

[dependencies]
axum = "0.6.0"
askama = "0.12"
tokio = { version = "1.0", features = ["full"] }
tracing = "0.1"
tracing-subscriber = { version = "0.3", features = ["env-filter"] }
reqwest = { version = "0.11.22", features = ["stream"] }
dotenvy = "0.15.7"
