[package]
name = "website"
version = "0.1.0"
edition = "2021"
publish = false

[dependencies]
axum = "0.6.0"
askama = "0.12"
tokio = { version = "1.0", features = ["full"] }
tracing = "0.1"
tracing-subscriber = { version = "0.3", features = ["env-filter"] }
reqwest = { version = "0.11.22", features = ["stream"] }
axum-tracing-opentelemetry = "0.14.1"
dotenvy = "0.15.7"
shared = { path = "../shared" }
anyhow = "1.0.75"
thiserror = "1.0.49"
reqwest-middleware = "0.2.3"
tracing-opentelemetry-instrumentation-sdk = "0.14.1"
reqwest-tracing = { version = "0.4.6", features = ["opentelemetry_0_20"] }
opentelemetry = { version = "0.20.0", features = ["trace"] }
opentelemetry-otlp = "0.13.0"
tracing-opentelemetry = "0.21.0"
axum_session_auth = "0.7.0"
serde = "1.0.189"
axum_session = "0.7.0"
