[package]
name = "api-server"
version = "0.1.0"
edition = "2021"
publish = false

[dependencies]
axum = "0.6.0"
tokio = { version = "1.0", features = ["full"] }
tracing = "0.1.37"
tracing-subscriber = { version = "0.3.17", features = ["json", "env-filter"] }
tower-http = { version = "0.3.4", features = ["trace"] }
dotenvy = "0.15.7"
axum-otel-metrics = "0.6.0"
axum-tracing-opentelemetry = "0.14.1"
init-tracing-opentelemetry = { version = "0.14.1", features = [
  "otlp",
  "tracing_subscriber_ext",
]}
opentelemetry = { version = "0.20.0", features = ["rt-tokio"] }
opentelemetry-otlp = { version = "0.13.0", optional = true }
tracing-opentelemetry-instrumentation-sdk = "0.14.1"
cargo-audit = "0.18.2"

[features]
otlp-over-http = [
  "opentelemetry-otlp/reqwest-client",
  "opentelemetry-otlp/reqwest-rustls",
  "opentelemetry-otlp/http-proto",
  "opentelemetry-otlp/tls"
  ]

[dev-dependencies]
cargo-audit = "0.18.2"
