[package]
name = "api-server"
version = "0.1.0"
edition = "2021"
publish = false

[[bin]]
name = "api-server"

[dependencies]
axum = { version = "0.6.0", features = ["headers", "macros"] }
tokio = { version = "1.0", features = ["full"] }
tracing = "0.1.37"
tracing-subscriber = { version = "0.3.17", features = ["json", "env-filter"] }
tower-http = { version = "0.4.4", features = ["trace", "cors", "auth"] }
dotenvy = "0.15.7"
axum-otel-metrics = "0.6.0"
axum-tracing-opentelemetry = "0.14.1"
init-tracing-opentelemetry = { version = "0.14.1", features = [
  "otlp",
  "tracing_subscriber_ext",
]}
opentelemetry = { version = "0.20.0", features = ["rt-tokio"] }
opentelemetry-otlp = { version = "0.13.0", optional = true }
tracing-opentelemetry = "0.21"
tracing-opentelemetry-instrumentation-sdk = "0.14.1"
cargo-audit = "0.18.2"
serde_json = "1.0.107"
serde = { version = "1.0.188", features = ["derive"] }
chrono = { version = "0.4.31", features = ["serde"] }
dotenv = "0.15.0"
uuid = { version = "1.4.1", features = ["serde", "v4"] }
sqlx = { version = "0.7.2", features = ["runtime-async-std-native-tls", "postgres", "chrono", "uuid"] }
shared = { path = "../shared" }
oasgen = { version = "0.13.0", features = ["axum"] }
anyhow = "1.0.75"
thiserror = "1.0.49"
axum-macros = "0.3.8"
argon2 = { version = "0.5.2", features = ["std"] }
secrecy = { version = "0.8", features = ["serde"] }
rand = { vesrion = "0.8.5", features = ["getrandom"]}
mockall = "0.11.4"
getrandom = "0.2.10"
aide = {version = "0.12.0", features = ["axum", "axum-extra", "bytes", "http"]}
schemars = {version = "0.8.16", features = ["uuid1"]}

[features]
otlp-over-http = ["opentelemetry-otlp/reqwest-client", "opentelemetry-otlp/reqwest-rustls", "opentelemetry-otlp/http-proto", "opentelemetry-otlp/tls"]

[dev-dependencies]
cargo-audit = "0.18.2"
