[package]
name = "api-server"
version = "0.1.0"
edition = "2021"
publish = false

[dependencies]
axum = "0.6.0"
tokio = { version = "1.0", features = ["full"] }
tracing = "0.1.37"
tracing-subscriber = { version = "0.3.17", features = ["json", "env-filter"] }
tower-http = { version = "0.3.4", features = ["trace"] }
dotenvy = "0.15.7"
