# We could use `@actions-rs/cargo` Action ability to automatically install `cross` tool
# in order to compile our application for some unusual targets.

on: [push, pull_request]

name: Cross-compile

jobs:
  build-test:
    name: Build and test
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: dtolnay/rust-toolchain@stable
      - env:
          SQLX_OFFLINE: "true"
        run: |
          cargo build
          cargo test
          cargo build --release

  build-mac:
    name: Build on mac
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v4
      - uses: dtolnay/rust-toolchain@stable
      - env:
          SQLX_OFFLINE: "true"
        run: |
          cargo build
