# We could use `@actions-rs/cargo` Action ability to automatically install `cross` tool
# in order to compile our application for some unusual targets.

on: [push, pull_request]

name: check fmt

jobs:
  cargo-fmt-check:
    runs-on: ubuntu-latest
    container: rust:slim
    steps:
      - uses: olix0r/cargo-action-fmt/setup@v2
      - uses: actions/checkout@v2
      - run: cargo check -q --message-format=json | cargo-action-fmt
