# We could use `@actions-rs/cargo` Action ability to automatically install `cross` tool
# in order to compile our application for some unusual targets.

on: [push, pull_request]

name: Check formatting

jobs:
  fmt:
    strategy:
      matrix:
        os:
          - ubuntu-latest
        services:
          - api
          - website
          - shared
    name: cargo fmt
    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v4
      - uses: dtolnay/rust-toolchain@stable
      - run: |
          cd ${{ matrix.services }}
          cargo fmt --check
          cargo audit
