# We could use `@actions-rs/cargo` Action ability to automatically install `cross` tool
# in order to compile our application for some unusual targets.

on: [push, pull_request]

name: Load test

jobs:
  k6_load_test:
    name: k6 Load Test
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4
        
      - uses: isbang/compose-action@v1.5.1
        with:
          compose-file: "./docker-compose.yaml"

      - run: |
          docker ps -a
          nc -vz 127.0.0.1 3000
      - name: Run local k6 test
        uses: grafana/k6-action@v0.2.0
        with:
          filename: load-test.js
